# The name of my app
name: college-affordability

# Give me http://nginx.lndo.site and https://nginx.lndo.site
proxy:
  appserver:
    - college-affordability.lndo.site

# Configure my services
services:

  # Create an nginx service called "appserver"
  appserver:

    # Use nginx version 1.12
    type: nginx:1.12

    # Optionally configure nginx to be able to also serve over https
    ssl: true

    # Optionally specify a webroot if your index.html is in a subdirectory
    webroot: dist

    overrides:
      services:
        ports: ['8888:80']
